### ISSUE TITLE
Регистрация

### ISSUE THREAD

**Issue by Lanaken** [bmstu-iu9/utp2018-5-2d-game#50]
1.Не совсем понятно, зачем нужна информация, про e-mail и пол.
2.Не совсем понятно, для чего нужна регистрация, так как  она ничего не дает.

**Comment by Mirzoeva** [comment]
Благодаря регистрации, сохраняются скиллы персонажа(такие как количество золота, здоровье и тд). При повторном открытии игры, можно будет зайти через созданный ранее профиль с сохраненными параметрами. На данный момент сохранение этих параметров обсуждается и изменяется. А пока создание профиля и вход в игру работают исправно.
