### ISSUE TITLE
Бой

### ISSUE THREAD

**Issue by Lanaken** [bmstu-iu9/utp2018-5-2d-game#52]
1.Весь текст в строке справа накладывается на старый текст,хотя по идее старый текст должен либо исчезать,либо передвигаться наверх(причем,как мне кажется, там даже место под это выделено).
2.Когда персонаж наносит удар,в строке пишется не кол-во урона, а undefined.
3.Так и должно быть,что боевая стойка через каждые 2-3 клика восстанавливается здоровье?

**Comment by Lanaken** [comment]
Ожидаемое поведение:

**Comment by januszlv** [comment]
По поводу строки хроники боя в описании коммита указано, что она пока не работает, там только её зачаток. Тем более всё перечисленное уже исправлено в последнем реквесте.

**Comment by januszlv** [comment]
Насчёт имени пользователя - если сначала зарегистрироваться, то оно там будет. Иначе используется имя по умолчанию.
