### ISSUE TITLE
Бой

### ISSUE THREAD

**Issue by Lanaken** [bmstu-iu9/utp2018-5-2d-game#77]
1)Когда у противника остается минимум здоровья он становится "неуязвимым".
2)"Боевая стойка" наносит противнику урон,должна ли она это делать?

**Comment by januszlv** [comment]
Да, боевая стойка должна наносить противнику урон, зависит от уровня навыка защиты героя и вашей личной удачи.
По поводу неуязвимости - проблема, действительно, в предметах, будем смотреть и чинить, спасибо
