### ISSUE TITLE
Поражение

### ISSUE THREAD

**Issue by Lanaken** [bmstu-iu9/utp2018-5-2d-game#78]
Сделайте пожалуйста так, чтобы после поражения все возвращалось на начальный экран регистрации, входа и тд.

**Comment by Lanaken** [comment]
Ну просто единственное как можно заново запустить игру это перезагрузить страницу, но тогда откроется не начальный экран, а сразу игра, я не уверен хорошо ли это. Нужно уточнить у Александра Владимировича.

**Comment by januszlv** [comment]
Может, лучше сделать кнопку "вернуться на главную

**Comment by Lanaken** [comment]
Ну да, можно и так.
